config/routes.rb
    patch :do_finish_signup, to: 'users/registrations#do_finish_signup'
  end

  root 'welcome#index'
  get '/welcome', to: 'welcome#welcome'
  get '/cuentasegura', to: 'welcome#verification', as: :cuentasegura

  resources :debates do
    member do
      post :vote
      put :flag
      put :unflag
      put :mark_featured
      put :unmark_featured
    end
    collection do
      get :map
      get :suggest
    end
  end

  resources :proposals do
    member do
      post :vote
      post :vote_featured
      put :flag
      put :unflag
      get :retire_form
      get :share
      patch :retire
    end
    collection do
      get :map
      get :suggest
      get :summary
    end
  end

  resources :comments, only: [:create, :show], shallow: true do
    member do
      post :vote
      put :flag
      put :unflag
    end
  end

  resources :budgets, only: [:show, :index] do
    resources :groups, controller: "budgets/groups", only: [:show]
    resources :investments, controller: "budgets/investments", only: [:index, :new, :create, :show, :destroy] do
      member do
        post :vote
      end
      collection { get :suggest }
    end
    resource :ballot, only: :show, controller: "budgets/ballots" do
      resources :lines, controller: "budgets/ballot/lines", only: [:create, :destroy]
    end
    resource :results, only: :show, controller: "budgets/results"
  end

  scope '/participatory_budget' do
    resources :spending_proposals, only: [:index, :new, :create, :show, :destroy], path: 'investment_projects' do
      post :vote, on: :member
    end
  end

  resources :follows, only: [:create, :destroy]

  resources :documents, only: [:destroy]

  resources :images, only: [:destroy]

  resources :direct_uploads, only: [:create]
  delete "direct_uploads/destroy", to: "direct_uploads#destroy", as: :direct_upload_destroy

  resources :stats, only: [:index]

  resources :legacy_legislations, only: [:show], path: 'legislations'

  resources :annotations do
    get :search, on: :collection
  end

  resources :polls, only: [:show, :index] do
    member do
      get :stats
      get :results
    end
    resources :questions, controller: 'polls/questions', shallow: true do
      post :answer, on: :member
    end
  end

  namespace :legislation do
    resources :processes, only: [:index, :show] do
      member do
        get :debate
        get :draft_publication
        get :allegations
        get :result_publication
      end
      resources :questions, only: [:show] do
        resources :answers, only: [:create]
      end
      resources :draft_versions, only: [:show] do
        get :go_to_version, on: :collection
        get :changes
        resources :annotations do
          get :search, on: :collection
          get :comments
          post :new_comment
        end
      end
    end
  end

  resources :users, only: [:show] do
    resources :direct_messages, only: [:new, :create, :show]
  end

  resource :account, controller: "account", only: [:show, :update, :delete] do
    get :erase, on: :collection
  end

  resources :notifications, only: [:index, :show] do
    put :mark_all_as_read, on: :collection
  end

  resources :proposal_notifications, only: [:new, :create, :show]

  resource :verification, controller: "verification", only: [:show]

  resources :communities, only: [:show] do
    resources :topics
  end

  scope module: :verification do
    resource :residence, controller: "residence", only: [:new, :create]
    resource :sms, controller: "sms", only: [:new, :create, :edit, :update]
    resource :verified_user, controller: "verified_user", only: [:show]
    resource :email, controller: "email", only: [:new, :show, :create]
    resource :letter, controller: "letter", only: [:new, :create, :show, :edit, :update]
  end

  resources :tags do
    collection do
      get :suggest
    end
  end

  namespace :admin do
    root to: "dashboard#index"
    resources :organizations, only: :index do
      get :search, on: :collection
      member do
        put :verify
        put :reject
      end
    end

    resources :hidden_users, only: [:index, :show] do
      member do
        put :restore
        put :confirm_hide
      end
    end

    resources :debates, only: :index do
      member do
        put :restore
        put :confirm_hide
      end
    end

    resources :proposals, only: :index do
      member do
        put :restore
        put :confirm_hide
      end
    end

    resources :spending_proposals, only: [:index, :show, :edit, :update] do
      member do
        patch :assign_admin
        patch :assign_valuators
      end

      get :summary, on: :collection
    end

    resources :budgets do
      member do
        put :calculate_winners
      end

      resources :budget_groups do
        resources :budget_headings do
        end
      end

      resources :budget_investments, only: [:index, :show, :edit, :update] do
        resources :budget_investment_milestones
        member { patch :toggle_selection }
      end
    end

    resources :signature_sheets, only: [:index, :new, :create, :show]

    resources :banners, only: [:index, :new, :create, :edit, :update, :destroy] do
      collection { get :search}
    end

    resources :comments, only: :index do
      member do
        put :restore
        put :confirm_hide
      end
    end

    resources :tags, only: [:index, :create, :update, :destroy]
    resources :officials, only: [:index, :edit, :update, :destroy] do
      get :search, on: :collection
    end

    resources :settings, only: [:index, :update]
    put :update_map, to: "settings#update_map"

    resources :moderators, only: [:index, :create, :destroy] do
      get :search, on: :collection
    end

    resources :valuators, only: [:index, :create] do
      get :search, on: :collection
      get :summary, on: :collection
    end

    resources :managers, only: [:index, :create, :destroy] do
      get :search, on: :collection
    end

    resources :administrators, only: [:index, :create, :destroy] do
      get :search, on: :collection
    end

    resources :users, only: [:index, :show]

    scope module: :poll do
      resources :polls do
        get :booth_assignments, on: :collection
        patch :add_question, on: :member

        resources :booth_assignments, only: [:index, :show, :create, :destroy] do
          get :search_booths, on: :collection
          get :manage, on: :collection
        end

        resources :officer_assignments, only: [:index, :create, :destroy] do
          get :search_officers, on: :collection
          get :by_officer, on: :collection
        end

        resources :recounts, only: :index
        resources :results, only: :index
      end

      resources :officers do
        get :search, on: :collection
      end

      resources :booths do
        get :available, on: :collection

        resources :shifts do
          get :search_officers, on: :collection
        end
      end

      resources :questions, shallow: true do
        resources :answers, except: [:index, :destroy], controller: 'questions/answers', shallow: true do
          resources :images, controller: 'questions/answers/images'
          resources :videos, controller: 'questions/answers/videos'
          get :documents, to: 'questions/answers#documents'
        end
        post '/answers/order_answers', to: 'questions/answers#order_answers'
      end
    end

    resources :verifications, controller: :verifications, only: :index do
      get :search, on: :collection
    end

    resource :activity, controller: :activity, only: :show
    resources :newsletters, only: :index do
      get :users, on: :collection
    end
    resource :stats, only: :show do
      get :proposal_notifications, on: :collection
      get :direct_messages, on: :collection
    end

    namespace :legislation do
      resources :processes do
        resources :questions
        resources :draft_versions
      end
    end

    namespace :api do
      resource :stats, only: :show
    end

    resources :geozones, only: [:index, :new, :create, :edit, :update, :destroy]

    namespace :site_customization do
      resources :pages, except: [:show]
      resources :images, only: [:index, :update, :destroy]
      resources :content_blocks, except: [:show]
    end
  end

  namespace :moderation do
    root to: "dashboard#index"

    resources :users, only: :index do
      member do
        put :hide
        put :hide_in_moderation_screen
      end
    end

    resources :debates, only: :index do
      put :hide, on: :member
      put :moderate, on: :collection
    end

    resources :proposals, only: :index do
      put :hide, on: :member
      put :moderate, on: :collection
    end

    resources :comments, only: :index do
      put :hide, on: :member
      put :moderate, on: :collection
    end
  end

  namespace :valuation do
    root to: "budgets#index"

    resources :spending_proposals, only: [:index, :show, :edit] do
      patch :valuate, on: :member
    end

    resources :budgets, only: :index do
      resources :budget_investments, only: [:index, :show, :edit] do
        patch :valuate, on: :member
      end
    end
  end

  namespace :management do
    root to: "dashboard#index"

    resources :document_verifications, only: [:index, :new, :create] do
      post :check, on: :collection
    end

    resources :email_verifications, only: [:new, :create]

    resources :user_invites, only: [:new, :create]

    resources :users, only: [:new, :create] do
      collection do
        delete :logout
        delete :erase
      end
    end

    resource :account, controller: "account", only: [:show]

    get 'sign_in', to: 'sessions#create', as: :sign_in

    resource :session, only: [:create, :destroy]
    resources :proposals, only: [:index, :new, :create, :show] do
      post :vote, on: :member
      get :print, on: :collection
    end

    resources :spending_proposals, only: [:index, :new, :create, :show] do

app/models/topic.rb
class Topic < ActiveRecord::Base
  acts_as_paranoid column: :hidden_at
  include ActsAsParanoidAliases

  belongs_to :community
  belongs_to :author, -> { with_hidden }, class_name: 'User', foreign_key: 'author_id'

  has_many :comments, as: :commentable

  validates :title, presence: true
  validates :description, presence: true
  validates :author, presence: true

  scope :sort_by_newest, -> { order(created_at: :desc) }
  scope :sort_by_oldest, -> { order(created_at: :asc) }
  scope :sort_by_most_commented, -> { reorder(comments_count: :desc) }

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  include CommentableActions

  before_action :load_community
  before_action :load_topic, only: [:show, :edit, :update, :destroy]

  has_orders %w{most_voted newest oldest}, only: :show

  skip_authorization_check only: :show
  load_and_authorize_resource except: :show

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params.merge(author: current_user, community_id: params[:community_id]))
    if @topic.save
      redirect_to community_path(@community), notice: I18n.t('flash.actions.create.topic')
    else
      render :new
    end
  end

  def show
    @commentable = @topic
    @comment_tree = CommentTree.new(@commentable, params[:page], @current_order)
    set_comment_flags(@comment_tree.comments)
  end

  def edit
  end

  def update
    if @topic.update(topic_params)
      redirect_to community_path(@community), notice: t('flash.actions.update.topic')
    else
      render :edit
    end
  end

  def destroy
    @topic.destroy
    redirect_to community_path(@community), notice: I18n.t('flash.actions.destroy.topic')
  end

  private

  def topic_params
    params.require(:topic).permit(:title, :description)
  end

  def load_community
    @community = Community.find(params[:community_id])
  end

  def load_topic
    @topic = Topic.find(params[:id])
  end
end

app/helpers/topics_helper.rb
module TopicsHelper

  def disabled_create_topic
    "disabled" unless current_user
  end

  def disabled_info_title
    t("community.show.sidebar.disabled_info_title") unless current_user
  end

end

app/views/topics/_comments.html.erb
<% cache [locale_and_user_status, @current_order, commentable_cache_key(@topic), @comment_tree.comments, @comment_tree.comment_authors, @topic.comments_count, @comment_flags] do %>
  <div class="row comments">

    <div id="comments" class="small-12 column">
      <%= render 'shared/wide_order_selector', i18n_namespace: "comments" %>

      <% @comment_tree.root_comments.each do |comment| %>
        <%= render 'comments/comment', comment: comment  %>
      <% end %>

      <%= paginate @comment_tree.root_comments %>

      <% if user_signed_in? %>
        <%= render 'comments/form', {commentable: @topic, parent_id: nil, toggeable: false} %>
      <% else %>
      <br>
      <div data-alert class="callout primary">
        <%= t("topics.show.login_to_comment",
            signin: link_to(t("votes.signin"), new_user_session_path),
            signup: link_to(t("votes.signup"), new_user_registration_path)).html_safe %>
        </div>
      <% end %>

    </div>
  </div>
<% end %>

app/views/topics/_filter_subnav.html.erb
<div class="row">
  <div class="small-12 column">

    <ul class="tabs" data-tabs id="topics-tabs">

      <li class="tabs-title is-active">
        <%= link_to "#tab-comments" do %>
          <h3>
            <%= t("community.topic.show.tab.comments_tab") %>
            <span class="js-comments-count">(<%= @topic.comments_count %>)</span>
          </h3>
        <% end %>
      </li>
      
    </ul>

  </div>
</div>

app/views/topics/_form.html.erb
<%= form_for([@community, @topic]) do |f| %>

  <%= render 'shared/errors', resource: @topic %>

  <div class="row">

    <div class="small-12 column">
      <%= f.label :title, t("community.topic.form.topic_title") %>
      <%= f.text_field :title, label: false %>
    </div>
    <div class="small-12 column">
      <%= f.label :description, t("community.topic.form.topic_description") %>
      <%= f.text_area :description, label: false %>
    </div>
    <div class="actions small-12 column">
      <%= f.submit(class: "button", value: t("community.topic.form.#{action_name}.submit_button")) %>
    </div>

  </div>

<% end %>

app/views/topics/_informative_text.html.erb
<h3><%= t("community.show.create_first_community_topic.first_theme") %></h3>

<% if user_signed_in? %>
  <%= t("community.show.create_first_community_topic.first_theme_not_logged_in") %>
<% else %>
  <div class="callout primary">
    <%= t("community.show.create_first_community_topic.sub_first_theme",
          link: link_to(t("community.show.create_first_community_topic.sign_link",
          org_name: setting['org_name']), new_user_session_path)).html_safe %>
  </div>
<% end %>

app/views/topics/_recommendations.html.erb
<div class="small-12 medium-3 column">

  <span class="icon-proposals float-right"></span>
  
  <h2><%= t("community.topic.sidebar.recommendations_title") %></h2>

  <ul class="recommendations">
    <li><%= t("community.topic.sidebar.recommendation_one") %></li>
    <li><%= t("community.topic.sidebar.recommendation_two") %></li>
    <li><%= t("community.topic.sidebar.recommendation_three") %></li>
  </ul>

</div>

app/views/topics/_topic.html.erb
<div id="<%= dom_id(topic) %>" class="panel column">
  
  <div class="small-8 column">

    <h3><%= link_to topic.title, community_topic_path(@community, topic) %></h3>

    <p class="topic-info">
      <span class="icon-comments"></span>&nbsp;
      <%= link_to t("community.show.topic.comments", count: topic.comments_count), community_topic_path(@community, topic, anchor: "comments") %>
      <span class="bullet">&nbsp;&bull;&nbsp;</span>
      <%= I18n.l topic.created_at.to_date %>
      <span class="bullet">&nbsp;&bull;&nbsp;</span>
      <%= topic.author.name %>
    </p>

  </div>

  <div class="small-4 column text-right">
    <% if topic.author == current_user %>
      <%= link_to t("community.show.topic.edit_button"), edit_community_topic_path(@community.id, topic), class: 'button small hollow' %>
      <%= link_to t("community.show.topic.destroy_button"), community_topic_path(@community.id, topic), method: :delete, class: 'button hollow alert small' %>
    <% end %>
  </div>

</div>

app/views/topics/_topics.html.erb
<% if topics.any? %>
  <div class="row column">
    <div class="order">
      <%= render 'shared/wide_order_selector', i18n_namespace: "comments" %>
    </div>
  </div>
<% else %>
  <%= render 'topics/informative_text', topics: topics %>
<% end %>

<% topics.each do |topic| %>
  <%= render 'topics/topic', topic: topic %>
<% end %>

app/views/topics/edit.html.erb
<div class="topic-form row">

  <div class="small-12 medium-9 column">
    <%= back_link_to community_path(@community) %>
    <h1><%= t("community.topic.edit") %></h1>
    <%= render "form" %>
  </div>

  <%= render "recommendations" %>
  
</div>

app/views/topics/new.html.erb
<div class="topic-new row">
  
  <div class="small-12 medium-9 column">
    <%= back_link_to community_path(@community) %>
    <h1><%= t("community.topic.create") %></h1>
    <%= render 'form' %>
  </div>

  <%= render "recommendations" %>

</div>

app/views/topics/show.html.erb
<div class="row topic-show">
  <div class="small-12 medium-12 column">

    <%= back_link_to community_path(@community) %>
    <br>

    <p><%= community_text(@community) %> <strong><%= community_title(@community) %></strong></p>
    <h1><%= @topic.title %></h1>
    <div class="topic-info">
      <p><%= @topic.description %></p>
      <%= render '/shared/author_info', resource: @topic %>

      <span class="bullet">&nbsp;&bull;&nbsp;</span>
      <%= l @topic.created_at.to_date %>
      <span class="bullet">&nbsp;&bull;&nbsp;</span>
      <span class="icon-comments"></span>&nbsp;
    </div>

    <div class="tabs-content" data-tabs-content="topics-tabs" role="tablist">
      <%= render "topics/filter_subnav" %>
      <div class="tabs-panel is-active" id="tab-comments">
        <%= render "topics/comments" %>
      </div>
    </div>
    
  </div>
</div>